version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/jest"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/next-shadcn"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vite-tailwind"
    schedule:
      interval: "weekly"
